apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
        - name: demo-app
          imagePullPolicy: Never
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.monitoring.svc:4318
